"""Adicionando colunas de notificacao

Revision ID: 56440eb7b67d
Revises: bfe5fa352487
Create Date: 2026-04-26 19:58:29.168793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56440eb7b67d'
down_revision = 'bfe5fa352487'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analises', schema=None) as batch_op:
        batch_op.add_column(sa.Column('metodo_notificacao', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('contato_notificacao', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analises', schema=None) as batch_op:
        batch_op.drop_column('contato_notificacao')
        batch_op.drop_column('metodo_notificacao')

    # ### end Alembic commands ###
