"""Criando banco com campos de contato separados

Revision ID: 8426d85483b0
Revises: 
Create Date: 2026-05-01 15:39:13.847553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8426d85483b0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matricula', sa.String(length=20), nullable=False),
    sa.Column('nome_aluno', sa.String(length=100), nullable=False),
    sa.Column('email_aluno', sa.String(length=120), nullable=False),
    sa.Column('whatsapp_aluno', sa.String(length=20), nullable=True),
    sa.Column('metodo_preferencial', sa.String(length=20), nullable=True),
    sa.Column('caminho_pdf', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('data_solicitacao', sa.DateTime(), nullable=True),
    sa.Column('metodo_notificacao', sa.String(length=20), nullable=True),
    sa.Column('contato_notificacao', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('cargo', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuarios')
    op.drop_table('analises')
    # ### end Alembic commands ###
