"""Migracao inicial: criacao das tabelas Usuario e AnaliseBarema

Revision ID: bfe5fa352487
Revises: 
Create Date: 2026-04-24 12:21:58.502003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfe5fa352487'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matricula', sa.String(length=20), nullable=False),
    sa.Column('nome_aluno', sa.String(length=100), nullable=False),
    sa.Column('caminho_pdf', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('data_solicitacao', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('cargo', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuarios')
    op.drop_table('analises')
    # ### end Alembic commands ###
